### ISSUE TITLE
Issue on page: Submission of SARS-Cov-2 raw reads to ENA in Galaxy

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/data_management_hub#102]
I would like to report an issue on the Submission of SARS-Cov-2 raw reads to ENA in Galaxy page at `/covid-19/sarscov2_submission`. Description of the issue:

Link to the example metadata is broken.
The `here` link [in this portion](https://github.com/ELIXIR-Belgium/rdm-guide/blob/5b1e313815dfed791981f9685a0523e59c8de209/pages/covid-19/sarscov2_submission.md?plain=1#L173-L174).

**Comment by bedroesb** [comment]
good catch!

**Comment by bedroesb** [comment]
This is fixed!
