### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/data_management_hub#51]
Could we use the "Credit" page in the sidebar to mention the authors of the website (Bert, Miguel and I)?
We have references at the end of each page, so I don't think we need a list of references also in the "Credit" page.

**Comment by bedroesb** [comment]
or we leave out credit and add our faces + names to the about us ? :) 

Something like this:
https://codepen.io/TheHorse/pen/JjYvZOz

![Screenshot from 2020-11-19 17-52-13](https://user-images.githubusercontent.com/44875756/99697375-fab83c00-2a8f-11eb-9fa0-4d4ac5f3f954.png)

**Comment by floradanna** [comment]
Yes, good idea.
Shall we delete the "Credit" page then?
