### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by roncoronimiguel** [ELIXIR-Belgium/data_management_hub#60]
on ENA page line 45
https://www.ebi.ac.uk/ena/submit/webin/sequence-checklist

**Comment by floradanna** [comment]
Thanks! Apparently, it is possible to download the checklist as spreadsheet only after LOG IN. I have specified this now and add the link to do the log in.

https://github.com/ELIXIR-Belgium/rdm-guide/pull/66/commits/7b277ec9cc067c69590938a4d1cf4d2360157495
